
import { describe, it, expect, beforeEach } from 'vitest';
import { renderHook, act, waitFor } from '@testing-library/react';
import { useGameState } from '../hooks/useGameState';

// Mock localStorage
const localStorageMock = (() => {
  let store: Record<string, string> = {};
  return {
    getItem: (key: string) => store[key] || null,
    setItem: (key: string, value: string) => { store[key] = value.toString(); },
    clear: () => { store = {}; },
    removeItem: (key: string) => { delete store[key]; }
  };
})();

Object.defineProperty(window, 'localStorage', { value: localStorageMock });

describe('Game Simulation (Local Engine)', () => {

    beforeEach(() => {
        window.localStorage.clear();
    });

    it('should initialize with a starter beast', async () => {
        const { result } = renderHook(() => useGameState());

        // Wait for the useEffect to run (starter beast creation)
        await waitFor(() => {
            expect(result.current.beasts.length).toBeGreaterThanOrEqual(1);
        }, { timeout: 2000 });

        expect(result.current.beasts[0].name).toBe('Neon Initiate');
        expect(result.current.coins).toBeGreaterThan(0);
    });

    it('should allow minting a new beast via Game Engine', async () => {
        const { result } = renderHook(() => useGameState());
        await waitFor(() => { expect(result.current.beasts.length).toBeGreaterThanOrEqual(1); });

        // Add coins to ensure minting is possible
        await act(async () => {
             result.current.debugMethods.addCoins(1000);
        });

        const initialCoins = result.current.coins;
        const mintPrice = result.current.calculateMintPrice();

        await act(async () => {
            await result.current.handleMint();
        });

        expect(result.current.beasts.length).toBeGreaterThanOrEqual(2);
        // Ensure new beast has valid stats generated by engine
        const newBeast = result.current.beasts[result.current.beasts.length - 1];
        expect(newBeast.stats.attack).toBeGreaterThan(0);
        expect(newBeast.name).toBeDefined();

        expect(result.current.coins).toBe(initialCoins - mintPrice);
    });

    it('should allow breeding two beasts', async () => {
        const { result } = renderHook(() => useGameState());
        await waitFor(() => { expect(result.current.beasts.length).toBeGreaterThanOrEqual(1); });

         // Add coins to ensure minting is possible
        await act(async () => {
             result.current.debugMethods.addCoins(5000);
        });

        // Get two beasts first
        await act(async () => {
            await result.current.handleMint(); // Beast 2
        });

        const p1 = result.current.beasts[0];
        const p2 = result.current.beasts[result.current.beasts.length - 1];

        await act(async () => {
            await result.current.handleBreed(p1, p2);
        });

        expect(result.current.beasts.length).toBeGreaterThanOrEqual(3);
        const child = result.current.beasts[result.current.beasts.length - 1];
        expect(child.generation).toBeGreaterThan(0);
        expect(child.description).toContain("Offspring of");
    });

    it('should simulate battle and grant rewards', async () => {
        const { result } = renderHook(() => useGameState());
        await waitFor(() => { expect(result.current.beasts.length).toBeGreaterThanOrEqual(1); });

        const beast = result.current.beasts[0];
        const initialCoins = result.current.coins;
        const initialExp = beast.exp;

        let battleResult;
        await act(async () => {
            battleResult = await result.current.handleBattle(beast);
        });

        expect(battleResult).toBeDefined();
        if (battleResult && battleResult.winnerId === beast.id) {
            expect(result.current.coins).toBeGreaterThan(initialCoins);
            expect(result.current.beasts[0].exp).toBeGreaterThan(initialExp);
        }

        // Verify logs exist and look real
        if (battleResult) {
            expect(battleResult.logs.length).toBeGreaterThan(0);
            expect(battleResult.logs[0].description).toBeDefined();
        }
    });
});
